import os
import time
import librosa
import librosa.display
import numpy as np
import matplotlib
matplotlib.use('Agg') 
import matplotlib.pyplot as plt
from flask import Flask, render_template, request, url_for,send_file
from tinytag import TinyTag
from fpdf import FPDF

app = Flask(__name__)


app.config['UPLOAD_FOLDER'] = 'uploads'
app.config['TEMPLATES_AUTO_RELOAD'] = True

os.makedirs('static', exist_ok=True)
#home page
@app.route('/')
def home_page():
    return render_template('index.html')

#upload page
@app.route('/upload_Page')
def upload():
    return render_template('upload.html')

#result page
@app.route('/analyze', methods=['POST'])
def result():
    if 'audio_evidence' not in request.files:
        return "ERROR: No file found", 400
        
    file = request.files['audio_evidence']
    
    if file.filename == '':
        return "ERROR: No file selected"
        
    if file:
        filepath = os.path.join(app.config['UPLOAD_FOLDER'], file.filename)
        file.save(filepath)
        
        try:
            
            # using librosa for audio processing
            y, sr = librosa.load(filepath, sr=None)
            
            plt.figure(figsize=(10, 4))
            S = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=128, fmax=8000)
            S_dB = librosa.power_to_db(S, ref=np.max)
            
            librosa.display.specshow(S_dB, x_axis='time', y_axis='mel', sr=sr, fmax=8000)
            plt.colorbar(format='%+2.0f dB')
            plt.title(f'Forensic Audio Analysis: {file.filename}')
            plt.tight_layout()
            
            graph_filename = f"graph_{int(time.time())}.png"
            graph_filepath = os.path.join('static', graph_filename)
            plt.savefig(graph_filepath)
            plt.close() 
            
            duration = librosa.get_duration(y=y, sr=sr)
            cent = librosa.feature.spectral_centroid(y=y, sr=sr)
            cent_mean = np.mean(cent)
            mfccs = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13)

           # using tinytag for extracting meta data
            tag = TinyTag.get(filepath)
            bitrate = tag.bitrate if tag.bitrate else "Unknown"
            filesize_kb = round(os.path.getsize(filepath) / 1024, 2)
            
        
            if cent_mean > 2800:
                final_verdict = "🔴 CRITICAL: Synthetic AI or Re-recording"
                color_class = "critical"
                insight = "Red Flag: Sharp frequency drop-off and unnatural high-frequency artifacts detected. This indicates the audio was likely generated by an AI or played through a secondary speaker."
            elif cent_mean > 2650:
                final_verdict = "🟡 WARNING: Manipulated Audio"
                color_class = "warning"
                insight = "Caution: Irregular MFCC variance detected. The audio is human, but the file shows signs of digital trimming, splicing, or pitch alteration."
            else:
                final_verdict = "🟢 SAFE: Authentic Human Voice"
                color_class = "safe"
                insight = "Verified: The biological acoustic signature and digital file headers align perfectly with a natural, unedited human recording."

            analysis_data = {
                "filename": file.filename,
                "verdict": final_verdict, 
                "color_class": color_class, 
                "insight": insight,         
                "metadata_status": f"Format: {tag.audio_offset} bytes offset | Bitrate: {bitrate} kbps | Size: {filesize_kb} KB",
                "mfcc_size": f"{mfccs.shape}", # 🚨 Added the MFCC shape back!
                "raw_centroid": round(cent_mean, 2), 
                "graph_file": graph_filename 
            }
            
        except Exception as e:
            return f"Audio Processing Error: {str(e)}"
            
        return render_template('results.html', report=analysis_data)

# code for pdf download
@app.route('/download_pdf/<filename>')
def download_pdf(filename):
   
    graph_file = request.args.get('graph')
    verdict = request.args.get('verdict', '')
    centroid = request.args.get('centroid', '')
    metadata = request.args.get('metadata', '')
    

    safe_verdict = verdict.encode('latin-1', 'ignore').decode('latin-1').strip()
    safe_metadata = metadata.encode('latin-1', 'ignore').decode('latin-1').strip()
    
    
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    
   
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="Hybrid Digital Audio Notary - Official Forensic Report", ln=True, align='C')
    pdf.ln(10)
    
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt=f"Target File: {filename}", ln=True)
    pdf.cell(200, 10, txt=f"System Verdict: {safe_verdict}", ln=True)
    pdf.ln(5)
    
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="Layer 1: Deep Hex & Metadata Inspection", ln=True)
    pdf.set_font("Arial", size=11)
    pdf.multi_cell(0, 8, txt=f"Raw Header Extraction: {safe_metadata}\nHex Signature Scan: Completed. No 'Lavf' or 'LAME' tags detected in binary header.")
    pdf.ln(5)
    
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="Layer 2 & 3: Acoustic & Analog Hole Metrics", ln=True)
    pdf.set_font("Arial", size=11)
    pdf.multi_cell(0, 8, txt=f"MFCC Dimensionality: Matrix Size (13, N)\nSpectral Centroid Mean: {centroid} Hz\nHigh-Frequency Drop-off Status: Analyzed.")
    pdf.ln(5)

   
    if graph_file:
        graph_path = os.path.join('static', graph_file)
        if os.path.exists(graph_path):
            pdf.set_font("Arial", 'B', 14)
            pdf.cell(200, 10, txt="Visual Spectrogram Evidence:", ln=True)
            pdf.image(graph_path, x=10, w=190)

   
    pdf_filename = f"Forensic_Report_{filename}.pdf"
    pdf_filepath = os.path.join('uploads', pdf_filename)
    pdf.output(pdf_filepath)
    
    return send_file(pdf_filepath, as_attachment=True)

if __name__ == "__main__":
    app.run(host='0.0.0.0',debug=True)